// Regenerates components/icons.tsx from the lucide-react copy already in node_modules
// (the one streamdown depends on). Vendoring avoids adding a runtime package.
// Usage: node docs/visual-overhaul/gen-icons.mjs
import { readFileSync, writeFileSync } from "node:fs";

const names = [
  "mic", "message-circle", "list-checks", "link", "users", "settings", "paperclip", "arrow-up", "plus", "smile", "image",
  "x", "check", "chevron-down", "chevron-right", "chevron-left", "play", "pause", "square", "download", "copy",
  "maximize-2", "file", "file-text", "music", "film", "wifi", "wifi-off", "sparkles", "wrench", "triangle-alert",
  "shield-alert", "clock", "search", "arrow-down", "arrow-left", "rotate-ccw", "refresh-cw", "volume-2", "volume-x",
  "vibrate", "moon", "zap", "circle-alert", "circle-check", "sliders-horizontal", "bell", "terminal",
  "hard-drive-download", "user-plus", "user-minus", "type", "orbit", "audio-lines", "hand", "ellipsis", "house", "bot",
  "book-open", "folder", "folder-open", "external-link", "hash", "file-image", "file-video-camera", "file-code", "history", "library",
];
const pascal = (n) => n.split("-").map((p) => p[0].toUpperCase() + p.slice(1)).join("");
const version = JSON.parse(readFileSync("node_modules/lucide-react/package.json", "utf8")).version;

let out = `/**
 * Icons vendored from Lucide (lucide-react v${version}), ISC License.
 * Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as part of Feather (MIT);
 * all other copyright (c) for Lucide are held by Lucide Contributors 2022.
 * Generated by docs/visual-overhaul/gen-icons.mjs. Vendored so the always-running dev server never needs a restart.
 */
import type { SVGProps } from "react";

type IconNode = [string, Record<string, string>][];
export type IconProps = SVGProps<SVGSVGElement> & { size?: number; strokeWidth?: number };

function make(node: IconNode, name: string) {
  function Icon({ size = 20, strokeWidth = 1.75, ...rest }: IconProps) {
    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden="true"
        {...rest}
      >
        {node.map(([tag, attrs], i) => {
          const Tag = tag as "path";
          return <Tag key={i} {...attrs} />;
        })}
      </svg>
    );
  }
  Icon.displayName = name;
  return Icon;
}

`;

for (const name of names) {
  const text = readFileSync(`node_modules/lucide-react/dist/esm/icons/${name}.js`, "utf8");
  const match = /const __iconNode = (\[[\s\S]*?\]);\n/.exec(text);
  if (!match) throw new Error(`no icon node in ${name}`);
  const node = Function(`return ${match[1]}`)().map(([tag, attrs]) => {
    const { key: _key, ...rest } = attrs;
    return [tag, rest];
  });
  out += `export const ${pascal(name)}Icon = make(${JSON.stringify(node)}, "${pascal(name)}Icon");\n`;
}

writeFileSync("components/icons.tsx", out);
console.log(`components/icons.tsx: ${names.length} icons from lucide-react ${version}`);
