<# : Update Chief Command Center (double-click). Batch part: run the PowerShell below from this same file.
@echo off
title Update Chief Command Center
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$f = '%~f0'; iex ([IO.File]::ReadAllText($f))"
echo.
pause
exit /b
#>
# Updates Chief Command Center to the newest release, keeping everything: chats, bots, settings and the Second Brain
# live outside the program and an update never touches them. One file to send a tester; nothing to unzip.
#
# 1. Finds the newest release on GitHub (no account or key needed) and downloads its package.
# 2. Checks the package is signed by Chief's publisher (the certificate fingerprint is built into this file) and
#    matches the checksum in its release description.
# 3. Trusts that certificate on this PC if it isn't yet (one administrator prompt, only then).
# 4. Asks Chief to close cleanly, installs the update on the drive Chief is on, and opens Chief again.
#
# Every step goes to a log (Desktop\Chief update log.txt) to send back if anything goes wrong.
# Generated by scripts/update-file.mjs from packaging/tester/update-chief.template.cmd. Plain ASCII, Windows
# PowerShell 5.1. CHIEF_UPDATE_DRYRUN=1 does everything up to the install and changes nothing; CHIEF_UPDATE_FORCE=1
# installs the newest version even when it's already installed (a damaged install).

$ErrorActionPreference = "Stop"
$Repo = "__REPO__"
$Fingerprint = "__FINGERPRINT__"
$Identity = "ChiefCommandCenter"
$DryRun = $env:CHIEF_UPDATE_DRYRUN -eq "1"
$Force = $env:CHIEF_UPDATE_FORCE -eq "1"
$Log = Join-Path ([Environment]::GetFolderPath("Desktop")) "Chief update log.txt"
$Work = Join-Path $env:TEMP "ChiefUpdate"

function Note($text) { Add-Content -Path $Log -Value ("{0} {1}" -f (Get-Date -Format s), $text) -ErrorAction SilentlyContinue }
function Say($text) { Write-Host $text; Note $text }
function Step($text) { Write-Host ""; Write-Host "== $text" -ForegroundColor Cyan; Note "== $text" }
function Done($text) { Write-Host ""; Write-Host $text -ForegroundColor Green; Note $text }
function Fail($text) {
  Write-Host ""
  Write-Host $text -ForegroundColor Red
  Write-Host "Nothing was changed unless it says so above. Please send the file 'Chief update log.txt' from your Desktop." -ForegroundColor Yellow
  Note "FAILED: $text"
  exit 1
}

Set-Content -Path $Log -Value ("Chief update log, " + (Get-Date -Format s)) -ErrorAction SilentlyContinue
Write-Host "Chief Command Center update" -ForegroundColor White
Write-Host "This gets the newest version and keeps all your chats, bots and settings."

try {
  Step "Checking this PC"
  if (-not [Environment]::Is64BitOperatingSystem) { Fail "Chief needs 64-bit Windows." }
  $build = [Environment]::OSVersion.Version.Build
  if ($build -lt 19041) { Fail "Chief needs Windows 10 version 2004 or later (this PC is build $build). Run Windows Update, then try again." }
  Say "Windows build $build, 64-bit: fine."
  $installed = Get-AppxPackage -Name $Identity | Sort-Object Version -Descending | Select-Object -First 1
  if ($installed) { Say "Chief $($installed.Version) is installed in $($installed.InstallLocation)." } else { Say "Chief isn't installed yet: this installs it." }

  # Windows PowerShell 5.1 can default to old TLS versions that GitHub refuses.
  [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
  Add-Type -AssemblyName System.Net.Http
  $handler = New-Object System.Net.Http.HttpClientHandler
  $handler.AllowAutoRedirect = $false
  $http = New-Object System.Net.Http.HttpClient($handler)
  $http.Timeout = [TimeSpan]::FromMinutes(60)
  $http.DefaultRequestHeaders.UserAgent.ParseAdd("ChiefCommandCenter-Updater")

  Step "Finding the newest version"
  # github.com/<repo>/releases/latest redirects to the newest release's page: no API call, so no rate limit.
  $res = $http.GetAsync("https://github.com/$Repo/releases/latest").Result
  $location = [string]$res.Headers.Location
  if ($location -notmatch "/tag/v(\d+\.\d+\.\d+)$") { Fail "Couldn't find the newest version on GitHub (answer $([int]$res.StatusCode)). Check the internet connection and try again." }
  $version = $Matches[1]
  Say "The newest version is $version."
  if ($installed -and -not $Force -and ([version]$installed.Version -ge [version]"$version.0")) {
    Done "Chief is already on $version (or newer). Nothing to do."
    if (-not $DryRun) { Start-Process ("shell:AppsFolder\" + $installed.PackageFamilyName + "!ChiefCommandCenter") }
    exit 0
  }
  $base = "https://github.com/$Repo/releases/download/v$version"
  $name = "ChiefCommandCenter-$version.msix"

  function Fetch($url) {
    # Follows GitHub's redirects to its download host.
    for ($i = 0; $i -lt 5; $i++) {
      $r = $http.GetAsync($url, [System.Net.Http.HttpCompletionOption]::ResponseHeadersRead).Result
      if ([int]$r.StatusCode -ge 300 -and [int]$r.StatusCode -lt 400) { $url = [string]$r.Headers.Location; continue }
      if (-not $r.IsSuccessStatusCode) { Fail "Downloading failed ($([int]$r.StatusCode)) for $url" }
      return $r
    }
    Fail "Too many redirects downloading $url"
  }

  $manifest = (Fetch "$base/release.json").Content.ReadAsStringAsync().Result | ConvertFrom-Json
  $expectedSha = [string]$manifest.package.sha256
  $size = [int64]$manifest.package.bytes
  if (-not $expectedSha -or $manifest.version -ne $version) { Fail "The release description for $version is unreadable. Try again later." }

  Step "Downloading Chief $version ($([math]::Round($size / 1MB)) MB)"
  New-Item -ItemType Directory -Force -Path $Work | Out-Null
  $drive = (Get-Item $Work).PSDrive
  if ($drive -and $drive.Free -lt ($size + 300MB)) { Fail "Not enough free space on drive $($drive.Name): it needs about $([math]::Round(($size + 300MB) / 1MB)) MB." }
  $file = Join-Path $Work $name
  $ready = (Test-Path $file) -and ((Get-Item $file).Length -eq $size) -and ((Get-FileHash $file -Algorithm SHA256).Hash -eq $expectedSha.ToUpperInvariant())
  if ($ready) {
    Say "Already downloaded."
  } else {
    $r = Fetch "$base/$name"
    $in = $r.Content.ReadAsStreamAsync().Result
    $out = [IO.File]::Create($file)
    try {
      $buffer = New-Object byte[] (1MB)
      $done = 0L
      $shown = -1
      while (($n = $in.Read($buffer, 0, $buffer.Length)) -gt 0) {
        $out.Write($buffer, 0, $n)
        $done += $n
        $pct = [int][math]::Floor($done * 100 / $size)
        if ($pct -ne $shown) { Write-Host -NoNewline ("`r  {0,3}%  ({1} of {2} MB)" -f $pct, [math]::Round($done / 1MB), [math]::Round($size / 1MB)); $shown = $pct }
      }
    } finally {
      $out.Close()
      $in.Close()
    }
    Write-Host ""
    Note "downloaded $done bytes"
  }

  Step "Checking the download"
  $hash = (Get-FileHash $file -Algorithm SHA256).Hash
  if ($hash -ne $expectedSha.ToUpperInvariant()) { Remove-Item $file -Force; Fail "The download didn't match its checksum (it may have been cut off). Run this again." }
  $signature = Get-AuthenticodeSignature -FilePath $file
  if (-not $signature.SignerCertificate) { Fail "The package isn't signed. Don't install it." }
  if (@("Valid", "UnknownError", "NotTrusted") -notcontains [string]$signature.Status) { Fail "The package's signature is broken ($($signature.Status)). Don't install it." }
  if ($signature.SignerCertificate.Thumbprint -ne $Fingerprint) { Fail "The package isn't signed by Chief's publisher (fingerprint $($signature.SignerCertificate.Thumbprint)). Don't install it." }
  Say "Checksum and publisher signature: fine."

  Step "Trusting Chief's publisher on this PC"
  $trusted = Get-ChildItem Cert:\LocalMachine\TrustedPeople | Where-Object { $_.Thumbprint -eq $Fingerprint }
  if ($trusted) {
    Say "Already trusted."
  } elseif ($DryRun) {
    Say "(dry run) would ask for administrator permission to trust the publisher."
  } else {
    Say "Windows will ask for administrator permission once, to trust Chief's publisher for app packages."
    $cer = Join-Path $Work "chief-publisher.cer"
    [IO.File]::WriteAllBytes($cer, $signature.SignerCertificate.Export([Security.Cryptography.X509Certificates.X509ContentType]::Cert))
    $cmd = "Import-Certificate -FilePath '" + $cer.Replace("'", "''") + "' -CertStoreLocation Cert:\LocalMachine\TrustedPeople | Out-Null"
    $p = Start-Process powershell.exe -Verb RunAs -Wait -PassThru -ArgumentList "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", $cmd
    $trusted = Get-ChildItem Cert:\LocalMachine\TrustedPeople | Where-Object { $_.Thumbprint -eq $Fingerprint }
    if (-not $trusted) { Fail "The publisher wasn't trusted (the administrator prompt was declined or failed, exit $($p.ExitCode))." }
    Say "Trusted."
  }

  if ($DryRun) { Done "Dry run: everything checks out; Chief $version would be installed now. Nothing was changed."; exit 0 }

  if ($installed) {
    Step "Closing Chief"
    $exe = Join-Path $installed.InstallLocation "app\Chief Command Center.exe"
    $running = Get-Process | Where-Object { $_.Path -and $_.Path.StartsWith($installed.InstallLocation, [StringComparison]::OrdinalIgnoreCase) }
    if ($running -and (Test-Path $exe)) {
      # Chief closes cleanly when asked (it stops its Hermes engine properly); Windows closes whatever is left.
      Start-Process -FilePath $exe -ArgumentList "--quit" -ErrorAction SilentlyContinue
      for ($i = 0; $i -lt 30; $i++) {
        Start-Sleep -Seconds 1
        $running = Get-Process | Where-Object { $_.Path -and $_.Path.StartsWith($installed.InstallLocation, [StringComparison]::OrdinalIgnoreCase) }
        if (-not $running) { break }
      }
    }
    Say ($(if ($running) { "Chief didn't close by itself in 30 seconds; Windows will close it for the update." } else { "Chief is closed." }))
  }

  Step "Installing Chief $version (about a minute or two)"
  $extra = @{}
  if ($installed) {
    # An update stays on the drive Chief is already on.
    $loc = [string]$installed.InstallLocation
    $vol = Get-AppxVolume | Where-Object { $loc.ToUpperInvariant().StartsWith(([string]$_.PackageStorePath).ToUpperInvariant() + "\") } | Select-Object -First 1
    if ($vol) { $extra.Volume = $vol }
  }
  Add-AppxPackage -Path $file -ForceApplicationShutdown -ForceUpdateFromAnyVersion @extra
  $now = Get-AppxPackage -Name $Identity | Sort-Object Version -Descending | Select-Object -First 1
  if (-not $now -or [version]$now.Version -lt [version]"$version.0") { Fail "Windows finished, but Chief is on $($now.Version) instead of $version." }
  Note "installed $($now.Version)"
  Remove-Item $file -Force -ErrorAction SilentlyContinue

  Done "Chief is updated to $version. Opening it now; your chats, bots and settings are all there."
  Start-Process ("shell:AppsFolder\" + $now.PackageFamilyName + "!ChiefCommandCenter")
  exit 0
} catch {
  Fail ("Something went wrong: " + $_.Exception.Message)
}
